version: 1.1.0

global-settings:
 time-source: internal-realtime
 ethernet-settings:
   access-mode: network-based

sil-kit:
  participant-name: CANoe4SW_SE
  config-file-path: ../SilKitConfig_CANoe.silkit.yaml

ethernet-networks:
  - name: Ethernet1    
    mapping: external-sil-kit

simulation-nodes:
  - name: SilKitDummyNode
    network-assignments:
      - network: Ethernet1
      