version: 4.0.0

global-settings:
 ethernet:
   access-mode: network-based

sil-kit:
  participant-name: CANoe4SW_SE
  config-file-path: ../SilKitConfig_CANoe.silkit.yaml

ethernet-networks:
  - name: Ethernet1    
    mapping: external-sil-kit

simulation-nodes:
  - name: SilKitDummyNode
    database-node: false
    network-assignments:
      - network: Ethernet1
