#!/bin/bash

set -e

while test $# -gt 0
do
    case "$1" in
        --with-time-sync) 
            PATH_TO_QEMU=./third_party/qemu/build/
            PLUGIN_ARGS="-icount shift=0  
                        -plugin /mnt/d/vfs/SilKit/vib-qemu-demos/build_wsl/time_sync/Plugin/libTimeSyncPlugin.so,HostToGuestPipe=/tmp/HostToGuestPipe,GuestToHostPipe=/tmp/GuestToHostPipe,TimeInMicroSeconds=1000
                        -L ./third_party/qemu/pc-bios/ "
            ;;
        *) echo "unknown argument $1"
            ;;
    esac
    shift
done

${PATH_TO_QEMU}qemu-system-x86_64              \
  -m 2048M                                                \
  -smp 2                                                  \
  -boot c 	                                          \
  -nographic                                              \
  -serial mon:stdio\
  -nic user,hostfwd=tcp::10022-:22,mac=00:11:22:33:44:55  \
  -chardev socket,id=ttySPI,server=on,wait=off,host=0.0.0.0,port=23456\
  -device isa-serial,chardev=ttySPI,id=serialSilKit,index=1\
  -netdev socket,id=mynet0,listen=:12345                                \
  -net nic,macaddr=52:54:56:53:4B:51,netdev=mynet0                      \
  -object filter-dump,id=tap_dump,netdev=mynet0,file=/tmp/qemu_linux_tap_dump \
  ${PLUGIN_ARGS} \
  -hda silkit-qemu-demos-guest.qcow2

exit 0
