version: "2.2.0"

global-settings:
 time-source: internal-realtime
 default-network-mapping: external-sil-kit

datasources:
  input-files:
  - file-path: ../CANoe/Datasource_qmp.vcdl

sil-kit:
  participant-name: CANoe4SW_SE
  config-file-path: ../SilKitConfig_CANoe.silkit.yaml

ethernet-networks:
  - name: Ethernet1

simulation-nodes:
  - name: SilKitDummyNode
    database-node: false
    network-assignments:
      - network: Ethernet1
        tcp-ip-stack-adapter:
          ipv4-settings: 
            address-configuration: static
            addresses:
             - address: "192.168.7.34"
               subnet-mask: "255.255.255.0"
               