# SPDX-FileCopyrightText: Copyright 2025 Vector Informatik GmbH
# SPDX-License-Identifier: MIT

macro(configure_silkit_adapter_version project_name)
    set(SILKIT_ADAPTER_VERSION_MAJOR 1)
    set(SILKIT_ADAPTER_VERSION_MINOR 2)
    set(SILKIT_ADAPTER_VERSION_PATCH 0)

    set(VERSION_STRING "${SILKIT_ADAPTER_VERSION_MAJOR}.${SILKIT_ADAPTER_VERSION_MINOR}.${SILKIT_ADAPTER_VERSION_PATCH}")

    set(PROJECT_VERSION_MAJOR ${SILKIT_ADAPTER_VERSION_MAJOR})
    set(PROJECT_VERSION_MINOR ${SILKIT_ADAPTER_VERSION_MINOR})
    set(PROJECT_VERSION_PATCH ${SILKIT_ADAPTER_VERSION_PATCH})
    set(PROJECT_VERSION ${VERSION_STRING})
endmacro()
