name: trigger sil-kit-adapters-ci
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      common_repo_commit:
        required: false
        type: string
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  trigger-adapters-ci:
    uses: ${{ secrets.CI_TESTING_WORKFLOW }}
    with:
      repository_under_test : ${{ secrets.ADAPTER_REPO_PATH }}
      branch_under_test: ${{ inputs.common_repo_commit != '' && 'main' || github.event.pull_request.head.ref }}
      common_repo_commit: ${{ inputs.common_repo_commit }}
      linux_scripts: |
        eth/demos/CANoe4SW_SE/run_all.sh
        chardev/demos/CANoe4SW_SE/run_all.sh
      windows_scripts: |
        eth/demos/CANoe4SW_SE/run_all.ps1
        chardev/demos/CANoe4SW_SE/run_all.ps1
    secrets: inherit
