name: trigger sil-kit-adapters-ci
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      common_repo_commit:
        required: false
        type: string
      branch_under_test:
        required: false
        type: string
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  trigger-adapters-ci:
    uses: pnd/sil-kit-adapters-ci-testing/.github/workflows/sil-kit-adapters-ci.yaml@main
    with:
      repository_under_test : 'pnd/sil-kit-adapters-qemu'
      branch_under_test: ${{ inputs.branch_under_test != '' && inputs.branch_under_test || (github.event_name == 'pull_request' && github.event.pull_request.head.ref || 'main') }}
      common_repo_commit: ${{ inputs.common_repo_commit }}
      linux_scripts: |
        eth/demos/CANoe4SW_SE/run_all.sh
        chardev/demos/CANoe4SW_SE/run_all.sh
      windows_scripts: |
        eth/demos/CANoe4SW_SE/run_all.ps1
        chardev/demos/CANoe4SW_SE/run_all.ps1
    secrets: inherit
